# Version 1.0.0

version: "3"

services:
  app:
    build: images/nginx/${NGINX_VERSION}
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - src:/var/www/html
      - sockdata:/sock
      # - ssldata:/etc/nginx/certs

  phpfpm:
    build: images/php/${PHP_VERSION}
    links:
      - db
    volumes: *appvolumes

  db:
    image: ${DB_VERSION}
    ports:
      - "3306:3306"
    env_file: env/db.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./images/mariadb/query_cache.cnf:/etc/mysql/conf.d/query_cache.cnf

  redis:
    image: redis:${REDIS_VERSION}

  elasticsearch:
    build: images/elasticsearch/${ELASTICSEARCH_VERSION}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: images/php/${PHP_VERSION}
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
